config/routes.rb
Rails.application.routes.draw do

  root to: 'check_ins#new'

  resources :check_in_images

  resources :check_ins

  resources :vessels

  resources :catches

  match '/reports', to: 'reports#index', via: 'get'

  match '/check_in/vessel/new/:check_in_id', to: 'vessels#new', via: 'get' 
  match '/check_in/vessel/edit/:id/:check_in_id', to: 'vessels#edit', via: 'get' 
  
  match '/check_in/check_in_image/new/:check_in_id', to: 'check_in_images#new', via: 'get'

  match '/check_in/catch/new/:check_in_id', to: 'catches#new', via: 'get'

end

app/models/catch.rb
# == Schema Information
#
# Table name: catches
#
#  id            :integer          not null, primary key
#  check_in_id   :integer
#  species       :string(255)
#  notes         :text
#  created_at    :datetime
#  updated_at    :datetime
#  fishing_style :string(255)
#

class Catch < ActiveRecord::Base
	belongs_to :check_in
end

app/controllers/catches_controller.rb
class CatchesController < ApplicationController
  before_action :set_catch, only: [:show, :edit, :update, :destroy]

  # GET /catches
  # GET /catches.json
  def index
    @catches = Catch.all
  end

  # GET /catches/1
  # GET /catches/1.json
  def show
  end

  # GET /catches/new
  def new
    @catch = Catch.new
  end

  # GET /catches/1/edit
  def edit
  end

  # POST /catches
  # POST /catches.json
  def create
    @catch = Catch.new(catch_params)
    check_in_id = @catch.check_in_id.to_s

    respond_to do |format|
      if @catch.save
        format.html { redirect_to "/check_ins/" + check_in_id, notice: 'Catch was successfully created.' }
        format.json { render :show, status: :created, location: @catch }
      else
        format.html { render :new }
        format.json { render json: @catch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /catches/1
  # PATCH/PUT /catches/1.json
  def update
    respond_to do |format|
      if @catch.update(catch_params)
        format.html { redirect_to @catch, notice: 'Catch was successfully updated.' }
        format.json { render :show, status: :ok, location: @catch }
      else
        format.html { render :edit }
        format.json { render json: @catch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /catches/1
  # DELETE /catches/1.json
  def destroy
    @catch.destroy
    respond_to do |format|
      format.html { redirect_to catches_url, notice: 'Catch was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_catch
      @catch = Catch.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def catch_params
      params.require(:catch).permit(:check_in_id, :species, :notes, :fishing_style)
    end
end

app/helpers/catches_helper.rb
module CatchesHelper
end

app/views/catches/_catches.html.erb
<% unless @check_in.catch %>
  <div class="form-group">
    <form action="/check_in/catch/new/<%=@check_in.id%>">
        <input type="submit" value="Add Catch Description + " class="btn btn-default btn-lg">
    </form>
  </div>
<% else %>
<div style="border-bottom: 1px solid #e5e5e5; margin-bottom: 15px;">
  <h4>Catch Description</h4>
  <div class="form-group">

    <% if @check_in.catch.species and @check_in.catch.species.length > 0 %>
      <strong>Species:</strong>
      <%= @check_in.catch.species %><br>
    <% end %>
    <strong>Fishing Style:</strong>
    <%= @check_in.catch.fishing_style %><br>

    <% if @check_in.catch.notes && @check_in.catch.notes.length > 0 %>
      <strong>Notes:</strong>
      <%= @check_in.catch.notes %>
    <% end %>
  </div>
</div>
<% end %>

app/views/catches/_form.html.erb
<%= form_for(@catch) do |f| %>
  <% if @catch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@catch.errors.count, "error") %> prohibited this catch from being saved:</h2>

      <ul>
      <% @catch.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if params[:check_in_id] %>
    <%= f.hidden_field :check_in_id, :value => params[:check_in_id].to_i %>
  <% end %>

  <div class="form-group">
    <%= f.label :fishing_style %><br>
    <%= f.select(:fishing_style, options_for_select([['Trawling', 'Trawling'], ['Netting', 'Netting'], ['Line Fishing','Line Fishing'], ['Trapping','Trapping'], ['Speargun','Speargun']]), {}, {:class => 'form-control'} ) %>
  </div>
  <div class="form-group">
    <%= f.label :species %><br>
    <%= f.text_field :species, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :notes %><br>
    <%= f.text_area :notes, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit "Submit", class: 'btn btn-default' %>
  </div>
<% end %>

app/views/catches/edit.html.erb
<h1>Editing catch</h1>

<%= render 'form' %>

<%= link_to 'Show', @catch %> |
<%= link_to 'Back', catches_path %>

app/views/catches/index.html.erb
<h1>Listing catches</h1>

<table>
  <thead>
    <tr>
      <th>Check in</th>
      <th>Species</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @catches.each do |catch| %>
      <tr>
        <td><%= catch.check_in_id %></td>
        <td><%= catch.species %></td>
        <td><%= catch.notes %></td>
        <td><%= link_to 'Show', catch %></td>
        <td><%= link_to 'Edit', edit_catch_path(catch) %></td>
        <td><%= link_to 'Destroy', catch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Catch', new_catch_path %>

app/views/catches/new.html.erb
<div class="container">

<h1>Specify Illegal Catch</h1>

<%= render 'form' %>

<%= link_to 'Back', catches_path %>

</div>

app/views/catches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Check in:</strong>
  <%= @catch.check_in_id %>
</p>

<p>
  <strong>Species:</strong>
  <%= @catch.species %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @catch.notes %>
</p>

<%= link_to 'Edit', edit_catch_path(@catch) %> |
<%= link_to 'Back', catches_path %>