config/routes.rb
Rails.application.routes.draw do

  root to: 'check_ins#new'

  resources :check_in_images

  resources :check_ins

  resources :vessels

  resources :catches

  match '/reports', to: 'reports#index', via: 'get'

  match '/check_in/vessel/new/:check_in_id', to: 'vessels#new', via: 'get' 
  match '/check_in/vessel/edit/:id/:check_in_id', to: 'vessels#edit', via: 'get' 
  
  match '/check_in/check_in_image/new/:check_in_id', to: 'check_in_images#new', via: 'get'

  match '/check_in/catch/new/:check_in_id', to: 'catches#new', via: 'get'

end

app/models/check_in.rb
# == Schema Information
#
# Table name: check_ins
#
#  id          :integer          not null, primary key
#  lat         :float
#  lng         :float
#  report_type :string(255)
#  notes       :text
#  created_at  :datetime
#  updated_at  :datetime
#  report_time :datetime
#

class CheckIn < ActiveRecord::Base

	has_one :catch
	has_one :vessel
	has_one :check_in_image


	searchable do
	    text :report_type
	    time :report_time
		latlon(:location) { Sunspot::Util::Coordinates.new(self.lat, self.lng) }
	end

	def report_time_formatted
		report_time.strftime("%Y-%m-%d %H:%M")
	end

	def has_catch?
		self.report_type == 'Poaching // Illegal Fishing'
	end

	def search_time
		report_time.to_time
	end
end

app/controllers/check_ins_controller.rb
class CheckInsController < ApplicationController
  before_action :set_check_in, only: [:show, :edit, :update, :destroy]

  # GET /check_ins
  # GET /check_ins.json
  def index
    @check_ins = CheckIn.all
  end

  # GET /check_ins/1
  # GET /check_ins/1.json
  def show
  end

  # GET /check_ins/new
  def new
    @check_in = CheckIn.new
  end

  # GET /check_ins/1/edit
  def edit
  end

  # POST /check_ins
  # POST /check_ins.json
  def create
    @check_in = CheckIn.new(check_in_params)

    respond_to do |format|
      if @check_in.save
        format.html { redirect_to @check_in, notice: 'Excellent. Tell us more.' }
        format.json { render :show, status: :created, location: @check_in }
      else
        format.html { render :new }
        format.json { render json: @check_in.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /check_ins/1
  # PATCH/PUT /check_ins/1.json
  def update
    respond_to do |format|
      if @check_in.update(check_in_params)
        format.html { redirect_to @check_in, notice: 'Check in was successfully updated.' }
        format.json { render :show, status: :ok, location: @check_in }
      else
        format.html { render :edit }
        format.json { render json: @check_in.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /check_ins/1
  # DELETE /check_ins/1.json
  def destroy
    @check_in.destroy
    respond_to do |format|
      format.html { redirect_to check_ins_url, notice: 'Check in was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_check_in
      @check_in = CheckIn.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def check_in_params
      params.require(:check_in).permit(:lat, :lng, :report_type, :notes, :report_time)
    end
end

app/helpers/check_ins_helper.rb
module CheckInsHelper
end

app/views/check_ins/_check_in_partial.html.erb
<div class="form-group" style="border-bottom: 1px solid #e5e5e5;">
  <h5><a href='/check_ins/<%=c.id%>'><%= c.report_type %></a></h5>
  <div class="form-group">
  	<span style="font-size: 12px; font-weight: normal; padding-left: 15px;"><%= c.report_time.strftime("%m/%d/%Y at %I:%M%p") %></span>
  </div>
</div>

app/views/check_ins/_form.html.erb
<%= form_for(@check_in) do |f| %>
  <% if @check_in.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@check_in.errors.count, "error") %> prohibited this check_in from being saved:</h2>

      <ul>
      <% @check_in.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- ######## Reason for checkin -->
  <div class="form-group">
    <%= f.label :report_time, "Time" %><br>
    <%= f.datetime_select :report_time, :default => DateTime.now %>
  </div>

  <div class="form-group">
    <%= f.label :report_type, "Reason" %><br>
    <%= f.select(:report_type, options_for_select([['Poaching // Illegal Fishing', 'Poaching // Illegal Fishing'], ['Habitat Degradation', 'Habitat Degradation'], ['Marine Debris','Marine Debris'], ['Poor Water Quality','Poor Water Quality'] ]), {}, {class: "form-control"}) %>
  </div>

  <!-- ######## Latitude and Longitude -->
  <div class="form-group"> 
    <div class="form-inline">
      <div class="form-group">
        <%= f.label :lat, "Latitude" %><br>
        <%= f.text_field :lat, :class => "form-control", :value => 30, :placeholder => "Latitude" %>
      </div>
      <div class="form-group">
        <%= f.label :lat, "Longitude" %><br>
        <%= f.text_field :lng, :class => "form-control", :value => 31, :placeholder => "Longitude" %>
      </div>
    </div>
  </div>

  <!-- ######## Map element --> 
  <div class="form-group">
    <div id="map-canvas" style="width: 100%; height: 120px; background: #eee; border-radius: 4px;"></div>
  </div>

  <!-- ######## Notes -->
  <div class="form-group">
    <%= f.label :notes %><br>
    <%= f.text_area :notes, :class => "form-control", :placeholder => "optional" %>
  </div>

  <!-- ######## Submit form --> 
  <div class="actions">
    <%= f.submit "Submit", :class => "btn btn-default" %>
  </div>

<% end %>

<script>
  var map;
  var marker;
  var coords;
  function initialize() {
    var mapOptions = {
      zoom: 2,
      center: new google.maps.LatLng(30, 31)
    };
    map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);

    coords = new google.maps.LatLng(30, 31);
    marker = new google.maps.Marker({
      position: coords,
      map: map,
      title:"You are here!"
    });
    navigator.geolocation.getCurrentPosition(success);
  }
  function success(position) {

    coords = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);
  
    var options = {
      zoom: 14,
      center: coords,
      mapTypeControl: false,
      navigationControlOptions: {
        style: google.maps.NavigationControlStyle.SMALL
      },
      mapTypeId: google.maps.MapTypeId.ROADMAP
    };
    map = new google.maps.Map(document.getElementById("map-canvas"), options);

    marker = new google.maps.Marker({
      position: coords,
      map: map,
      title:"You are here!"
    });

    document.getElementById("check_in_lat").value = position.coords.latitude;
    document.getElementById("check_in_lng").value = position.coords.longitude;    

  }

  var ready;
  ready = function() {
    document.getElementById("check_in_nav").setAttribute("class", "active");
    initialize();
  };

  //workaround for turbolinks
  $(document).ready(ready);
  $(document).on('page:load', ready);
  //google.maps.event.addDomListener(window, 'load', initialize);

</script>

app/views/check_ins/edit.html.erb
<div class="container">

<h1>Editing check_in</h1>

<%= render 'form' %>

<%= link_to 'Show', @check_in %> |
<%= link_to 'Back', check_ins_path %>

</div>

app/views/check_ins/index.html.erb
<div class="container">

  <h1>Listing check_ins</h1>

  <table class="table table-striped table-bordered table-condensed"> 
    <thead>
      <tr>
        <th>Lat</th>
        <th>Lng</th>
        <th>Type</th>
        <th>Notes</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @check_ins.each do |check_in| %>
        <tr>
          <td><%= check_in.lat %></td>
          <td><%= check_in.lng %></td>
          <td><%= check_in.report_type %></td>
          <td><%= check_in.notes %></td>
          <td><%= link_to 'Show', check_in %></td>
          <td><%= link_to 'Edit', edit_check_in_path(check_in) %></td>
          <td><%= link_to 'Destroy', check_in, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Check in', new_check_in_path %>

</div>

app/views/check_ins/new.html.erb
<div class="container">

<h1>Check In</h1>

<div class="form-group">
	<%= render 'form' %>
</div>

</div>

app/views/check_ins/show.html.erb
<div class="container">

<% if notice && notice.length > 0 %>
<div class="alert alert-info alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
<p id="notice"><%= notice %></p>
</div>
<% end %>


<div class="form-group" style="border-bottom: 1px solid #e5e5e5;">
	<h2>
  		<%= @check_in.report_type %>
      <span style="font-size: 12px; font-weight: normal; padding-left: 15px;"><%= @check_in.report_time.strftime("%m/%d/%Y at %I:%M%p") %></span>
	</h2>
</div>

<!-- ######## Latitude and Longitude -->
<div class="form-group"> 
  <%= label :lat, "Location" %><br>
  <input class="form-control" id="disabledInput" type="text" placeholder="<%= @check_in.lat %>, <%= @check_in.lng %>" disabled>
</div>

<!-- ######## Map element --> 
<div class="form-group">
  <div id="map-canvas" style="width: 100%; height: 120px; background: #eee; border-radius: 4px;"></div>
</div>

<% if @check_in.notes && @check_in.notes.length > 0 %>
	<div class="form-group">
  		<strong>Notes:</strong>
  		<%= @check_in.notes %>
	</div>
<% end %>

<% if @check_in.has_catch? %>
  <%= render :partial => 'catches/catches' %>
<% end %>

<% if @check_in.report_type == "Poaching // Illegal Fishing" %>
  <%= render :partial => '/vessels/vessel_partial' %>
<% end %>

<% unless @check_in.check_in_image %>
  <div class="form-group">
    <form action="/check_in/check_in_image/new/<%=@check_in.id%>">
        <input type="submit" value="Add Image + " class="btn btn-default btn-lg">
    </form>
  </div>
<% else %>
   <%= render :partial => 'check_in_images/images', locals: { image: @check_in.check_in_image } %>
<% end %>


</div>

<script>
  var map;
  function initialize() {
    var mapOptions = {
      zoom: 15,
      draggable: false,
      zoomControl: false,
      scrollwheel: false,
      disableDoubleClickZoom: true,
      center: new google.maps.LatLng(<%= @check_in.lat %>, <%= @check_in.lng %>)
    };
    map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);

    var coords = new google.maps.LatLng(<%= @check_in.lat %>, <%= @check_in.lng %>);

    var marker = new google.maps.Marker({
      position: coords,
      map: map,
      title:"Check in was here!"
    });

  }

  var ready;
  ready = function() {
    initialize();
  };

  //workaround for turbolinks
  $(document).ready(ready);
  $(document).on('page:load', ready);
  //google.maps.event.addDomListener(window, 'load', initialize);

</script>