config/routes.rb
Rails.application.routes.draw do

  root to: 'check_ins#new'

  resources :check_in_images

  resources :check_ins

  resources :vessels

  resources :catches

  match '/reports', to: 'reports#index', via: 'get'

  match '/check_in/vessel/new/:check_in_id', to: 'vessels#new', via: 'get' 
  match '/check_in/vessel/edit/:id/:check_in_id', to: 'vessels#edit', via: 'get' 
  
  match '/check_in/check_in_image/new/:check_in_id', to: 'check_in_images#new', via: 'get'

  match '/check_in/catch/new/:check_in_id', to: 'catches#new', via: 'get'

end

app/models/vessel.rb
# == Schema Information
#
# Table name: vessels
#
#  id             :integer          not null, primary key
#  check_in_id    :integer
#  vessel_type    :string(255)
#  vessel_number  :string(255)
#  vessel_name    :string(255)
#  estimated_crew :string(255)
#  notes          :text
#  created_at     :datetime
#  updated_at     :datetime
#  length         :string(255)
#  color          :string(255)
#

class Vessel < ActiveRecord::Base

	belongs_to :check_in

end

app/controllers/vessels_controller.rb
class VesselsController < ApplicationController
  before_action :set_vessel, only: [:show, :edit, :update, :destroy]

  # GET /vessels
  # GET /vessels.json
  def index
    @vessels = Vessel.all
  end

  # GET /vessels/1
  # GET /vessels/1.json
  def show
  end

  # GET /vessels/new
  def new
    @vessel = Vessel.new
  end

  # GET /vessels/1/edit
  def edit
  end

  # POST /vessels
  # POST /vessels.json
  def create
    @vessel = Vessel.new(vessel_params)
    check_in_id = @vessel.check_in_id.to_s

    respond_to do |format|
      if @vessel.save
        format.html { redirect_to "/check_ins/" + check_in_id, notice: 'Vessel was successfully created.' }
        format.json { render :show, status: :created, location: @vessel }
      else
        format.html { render :new }
        format.json { render json: @vessel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vessels/1
  # PATCH/PUT /vessels/1.json
  def update
    respond_to do |format|
      if @vessel.update(vessel_params)
        format.html { redirect_to @vessel, notice: 'Vessel was successfully updated.' }
        format.json { render :show, status: :ok, location: @vessel }
      else
        format.html { render :edit }
        format.json { render json: @vessel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vessels/1
  # DELETE /vessels/1.json
  def destroy
    @vessel.destroy
    respond_to do |format|
      format.html { redirect_to vessels_url, notice: 'Vessel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vessel
      @vessel = Vessel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vessel_params
      params.require(:vessel).permit(:check_in_id, :vessel_type, :vessel_number, :vessel_name, :estimated_crew, :notes, :length, :color)
    end
end

app/helpers/vessels_helper.rb
module VesselsHelper
end

app/views/vessels/_form.html.erb
<%= form_for(@vessel) do |f| %>
  <% if @vessel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vessel.errors.count, "error") %> prohibited this vessel from being saved:</h2>

      <ul>
      <% @vessel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if params[:check_in_id] %>
    <%= f.hidden_field :check_in_id, :value => params[:check_in_id].to_i %>
  <% end %>

  <!-- ######## Vessel type -->
  <div class="form-group">
    <%= f.label :vessel_type %><br>
    <%= f.select(:vessel_type, options_for_select([['Commercial Trawler', 'Commercial Trawler'], ['Seiner', 'Seiner'], ['Line Vessel','Line Vessel'], ['Jigger','Jigger'], ['Dredge','Dredge'], ['Small // Artisan','Small // Artisan'] ]), {}, {:class => 'form-control'} ) %>
  </div>

  <!-- ######## Vessel length -->
  <div class="form-group">
    <%= f.label :length, 'Vessel Length' %><br>
    <%= f.select(:length, options_for_select([['Smaller than 6 meters (20 ft)', 'Smaller than 6 meters (20 ft)'], ['6 - 12 meters (20 - 40 ft)', '6 - 12 meters (20 - 40 ft)'], ['12 - 18 meters (40 - 60 ft)','12 - 18 meters (40 - 60 ft)'], ['Bigger than 18 meters (60 ft)','Bigger than 18 meters (60 ft)'] ]), {}, {:class => 'form-control'} ) %>
  </div>

  <!-- ######## Vessel length -->
  <div class="form-group">
    <%= f.label :estimated_crew, 'Number of Crew Members' %><br>
    <%= f.select(:estimated_crew, options_for_select([['Less than 3', 'Less than 3'], ['4 to 10', '4 to 10'], ['11 to 20','11 to 20'], ['More than 20','More than 20'] ]), {}, {:class => 'form-control'} ) %>
  </div>
  <div class="form-group">
    <%= f.label :color, "Vessel Color" %><br>
    <%= f.text_field :color, :class => "form-control", :placeholder => " ex. Green and Red" %>
  </div>
  <div class="form-group">
    <%= f.label :vessel_number %><br>
    <%= f.text_field :vessel_number, :class => "form-control", :placeholder => " If available" %>
  </div>
  <div class="form-group">
    <%= f.label :vessel_name %><br>
    <%= f.text_field :vessel_name, :class => "form-control", :placeholder => " If available" %>
  </div>
  <div class="form-group">
    <%= f.label :notes %><br>
    <%= f.text_area :notes, :class => "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit "Submit", :class => "btn btn-default" %>
  </div>
<% end %>

app/views/vessels/_vessel_partial.html.erb
<% unless @check_in.vessel %>
  <div class="form-group">
    <form action="/check_in/vessel/new/<%=@check_in.id%>">
        <input type="submit" value="Add Vessel Description + " class="btn btn-default btn-lg">
    </form>
  </div>
<% else %>
<div style="border-bottom: 1px solid #e5e5e5; margin-bottom: 15px;">
  <h4>Vessel Description</h4>
  <div class="form-group">

    <strong>Vessel Type:</strong>
    <%= @check_in.vessel.vessel_type %><br>

    <strong>Length:</strong>
    <%= @check_in.vessel.length %><br>

    <% if @check_in.vessel.color && @check_in.vessel.color.length > 0 %>
      <strong>Color:</strong>
      <%= @check_in.vessel.color %><br>
    <% end %>

    <strong>Number of Crew:</strong>
    <%= @check_in.vessel.estimated_crew %><br>

    <% if @check_in.vessel.vessel_number && @check_in.vessel.vessel_number.length > 0 %>
      <strong>Vessel ID Number:</strong>
      <%= @check_in.vessel.vessel_number %><br>
    <% end %>

    <% if @check_in.vessel.vessel_name && @check_in.vessel.vessel_name.length > 0 %>
      <strong>Vessel Name:</strong>
      <%= @check_in.vessel.vessel_name %><br>   
    <% end %>

    <% if @check_in.vessel.notes && @check_in.vessel.notes.length > 0 %>
      <strong>Notes:</strong>
      <%= @check_in.vessel.notes %>
    <% end %>
  </div>
</div>
<% end %>

app/views/vessels/edit.html.erb
<div class="container">

<h1>Editing vessel</h1>

<%= render 'form' %>

<%= link_to 'Show', @vessel %> |
<%= link_to 'Back', vessels_path %>

</div>

app/views/vessels/index.html.erb
<h1>Listing vessels</h1>

<table>
  <thead>
    <tr>
      <th>Check in</th>
      <th>Vessel type</th>
      <th>Vessel number</th>
      <th>Vessel name</th>
      <th>Estimated crew</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vessels.each do |vessel| %>
      <tr>
        <td><%= vessel.check_in_id %></td>
        <td><%= vessel.vessel_type %></td>
        <td><%= vessel.vessel_number %></td>
        <td><%= vessel.vessel_name %></td>
        <td><%= vessel.estimated_crew %></td>
        <td><%= vessel.notes %></td>
        <td><%= link_to 'Show', vessel %></td>
        <td><%= link_to 'Edit', edit_vessel_path(vessel) %></td>
        <td><%= link_to 'Destroy', vessel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vessel', new_vessel_path %>

app/views/vessels/new.html.erb
<div class="container">

<h1>Vessel Details</h1>

<%= render 'form' %>

<% if params[:check_in_id] %>
	<br><%= link_to 'Back', '/check_ins/' + params[:check_in_id] %>
<% end %>

</div>

app/views/vessels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Check in:</strong>
  <%= @vessel.check_in_id %>
</p>

<p>
  <strong>Vessel type:</strong>
  <%= @vessel.vessel_type %>
</p>

<p>
  <strong>Vessel number:</strong>
  <%= @vessel.vessel_number %>
</p>

<p>
  <strong>Vessel name:</strong>
  <%= @vessel.vessel_name %>
</p>

<p>
  <strong>Estimated crew:</strong>
  <%= @vessel.estimated_crew %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @vessel.notes %>
</p>

<%= link_to 'Edit', edit_vessel_path(@vessel) %> |
<%= link_to 'Back', vessels_path %>