config/routes.rb
Rails.application.routes.draw do

  root to: 'check_ins#new'

  resources :check_in_images

  resources :check_ins

  resources :vessels

  resources :catches

  match '/reports', to: 'reports#index', via: 'get'

  match '/check_in/vessel/new/:check_in_id', to: 'vessels#new', via: 'get' 
  match '/check_in/vessel/edit/:id/:check_in_id', to: 'vessels#edit', via: 'get' 
  
  match '/check_in/check_in_image/new/:check_in_id', to: 'check_in_images#new', via: 'get'

  match '/check_in/catch/new/:check_in_id', to: 'catches#new', via: 'get'

end

app/models/check_in_image.rb
# == Schema Information
#
# Table name: check_in_images
#
#  id                 :integer          not null, primary key
#  check_in_id        :integer
#  description        :text
#  created_at         :datetime
#  updated_at         :datetime
#  image_file_name    :string(255)
#  image_content_type :string(255)
#  image_file_size    :integer
#  image_updated_at   :datetime
#

class CheckInImage < ActiveRecord::Base

	belongs_to :check_in

	has_attached_file :image, :styles => { :large => "1024x1024>", :medium => "600x600>", :small => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

	validates_attachment_presence :image	

end

app/controllers/check_in_images_controller.rb
class CheckInImagesController < ApplicationController
  before_action :set_check_in_image, only: [:show, :edit, :update, :destroy]

  # GET /check_in_images
  # GET /check_in_images.json
  def index
    @check_in_images = CheckInImage.all
  end

  # GET /check_in_images/1
  # GET /check_in_images/1.json
  def show
  end

  # GET /check_in_images/new
  def new
    @check_in_image = CheckInImage.new
  end

  # GET /check_in_images/1/edit
  def edit
  end

  # POST /check_in_images
  # POST /check_in_images.json
  def create
    @check_in_image = CheckInImage.new(check_in_image_params)
    check_in_id = @check_in_image.check_in_id.to_s

    respond_to do |format|
      if @check_in_image.save
        format.html { redirect_to "/check_ins/" + check_in_id, notice: 'Check in image was successfully created.' }
        format.json { render :show, status: :created, location: @check_in_image }
      else
        format.html { render :new }
        format.json { render json: @check_in_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /check_in_images/1
  # PATCH/PUT /check_in_images/1.json
  def update
    respond_to do |format|
      if @check_in_image.update(check_in_image_params)
        format.html { redirect_to @check_in_image, notice: 'Check in image was successfully updated.' }
        format.json { render :show, status: :ok, location: @check_in_image }
      else
        format.html { render :edit }
        format.json { render json: @check_in_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /check_in_images/1
  # DELETE /check_in_images/1.json
  def destroy
    @check_in_image.destroy
    respond_to do |format|
      format.html { redirect_to check_in_images_url, notice: 'Check in image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_check_in_image
      @check_in_image = CheckInImage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def check_in_image_params
      params.require(:check_in_image).permit(:check_in_id, :description, :image)
    end
end

app/helpers/check_in_images_helper.rb
module CheckInImagesHelper
end

app/views/check_in_images/_form.html.erb
<%= form_for(@check_in_image) do |f| %>
  <% if @check_in_image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@check_in_image.errors.count, "error") %> prohibited this check_in_image from being saved:</h2>

      <ul>
      <% @check_in_image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if params[:check_in_id] %>
    <%= f.hidden_field :check_in_id, :value => params[:check_in_id].to_i %>
  <% end %>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>

  <div class="form-group">
    <%= f.submit "Submit", :class => "btn btn-default" %>
  </div>
<% end %>

app/views/check_in_images/_images.html.erb
<div style="border-bottom: 1px solid #e5e5e5; margin-bottom: 15px;">
  <h4>Image</h4>
  <div class="form-group">
  	<%= image_tag image.image.url(:small) %>
  	<% if @check_in.check_in_image.description && @check_in.check_in_image.description.length > 0 %>
    	<br><strong>Description:</strong>
    	<%= @check_in.check_in_image.description %>
    <% end %>
  </div>
</div>

app/views/check_in_images/edit.html.erb
<h1>Editing check_in_image</h1>

<%= render 'form' %>

<%= link_to 'Show', @check_in_image %> |
<%= link_to 'Back', check_in_images_path %>

app/views/check_in_images/index.html.erb
<h1>Listing check_in_images</h1>

<table>
  <thead>
    <tr>
      <th>Check in</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @check_in_images.each do |check_in_image| %>
      <tr>
        <td><%= check_in_image.check_in_id %></td>
        <td><%= check_in_image.description %></td>
        <td><%= link_to 'Show', check_in_image %></td>
        <td><%= link_to 'Edit', edit_check_in_image_path(check_in_image) %></td>
        <td><%= link_to 'Destroy', check_in_image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Check in image', new_check_in_image_path %>

app/views/check_in_images/new.html.erb
<div class='container'>

<h1>Upload an Image</h1>

<%= render 'form' %>

<% if params[:check_in_id] %>
<%= link_to 'Back', '/check_ins/' + params[:check_in_id] %>
<% end %>

</div>

app/views/check_in_images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Check in:</strong>
  <%= @check_in_image.check_in_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @check_in_image.description %>
</p>

<%= link_to 'Edit', edit_check_in_image_path(@check_in_image) %> |
<%= link_to 'Back', check_in_images_path %>